name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: dokkai-craft  # 修正

      - name: Run Build
        run: npm run build
        working-directory: dokkai-craft  # 修正

      - name: Run Lint
        run: npm run lint
        working-directory: dokkai-craft  # 修正
